

# Site settings
title: Paul Samsotha Blog
email: paulsamsotha.dev@gmail.com
description: >
  Paul Samsotha's developer blog.
baseurl: ""
url: "https://psamsotha.github.io" # the base hostname & protocol for your site
paginate: 6
paginate_path: "/archive/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Paul Samsotha"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [node_modules, package.json, gulpfile.js]
gems: [jekyll-paginate, jekyll-sitemap]

