

# Site settings
title: Paul Samsotha Blog
email: paulsamsotha.dev@gmail.com
description: >
  Paul Samsotha's developer blog.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      author: "Paul Samsotha"

# Build settings
markdown: kramdown
exclude: [node_modules, package.json, gulpfile.js]
